name: book_my_movie
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #DI
  get_it: ^7.6.7

  #Image
  cached_network_image: ^3.3.1

  #Freezed Data models
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  freezed_annotation: ^2.4.1

  #Offline DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #images
  flutter_svg: ^2.0.9

  #Shimmer effect
  shimmer: ^3.0.0

  #Logging
  logging: ^1.2.0

  #observer
  navigation_history_observer: ^1.1.0

  shared_preferences: ^2.2.2

  #Utils
  intl: ^0.19.0

  #Network
  internet_connection_checker: ^1.0.0+1
  dio: ^5.4.0
  dio_http2_adapter: ^2.4.0
  pretty_dio_logger: ^1.3.1

  #State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  carousel_slider: ^4.2.1

  #Video Player
  youtube_player_flutter: ^8.1.2

  #Animation
  lottie: ^3.0.0

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  hive_generator: ^2.0.1

  #Assest
  flutter_gen: ^5.4.0

flutter_gen:

  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  
  colors:
    inputs:
      - assets/colors/colors.xml
      
  # Optional
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true

  assets:

    - assets/
    - assets/images/
    - assets/svg/
    - assets/icons/
    - assets/json/
